services:
  mysql:
    image: mysql:8.0
    container_name: mrpz2_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mrpz2_ebanci
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mrpz2_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mrpz2_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - mrpz2_network

volumes:
  mysql_data:
    driver: local

networks:
  mrpz2_network:
    driver: bridge